install.packages("effectsize")
install.packages("car")
install.packages("pwr")
install.packages("multcomp")
install.packages("psych")
install.packages("phia")
install.packages("countrycode")

library(effectsize)
library(car)
library(pwr)
library(multcomp)
library(psych)
library(phia)
library(countrycode)
